// Data Konfigurasi Instansi Layanan Darurat - PRACI SIAGA
// ⚠️  Update nomor sesuai data resmi terbaru

const EMERGENCY_SERVICES = [
  {
    id: "polsek-pracimantoro",
    name: "Polsek Pracimantoro",
    shortName: "POLSEK",
    category: "keamanan",
    categoryLabel: "Keamanan & Ketertiban",
    phone: "110",
    phoneDisplay: "110 (Darurat Polri)",
    phoneRaw: "110",
    whatsapp: "+6285196201594", // WA Polsek Pracimantoro
    phoneAlt: "+62 851-9620-1594", // Nomor WA
    description:
      "Penanganan tindak kriminalitas, pencurian, kecelakaan lalu lintas, gangguan ketertiban umum, kekerasan dalam rumah tangga, dan laporan ancaman keamanan di wilayah Kecamatan Pracimantoro.",
    keywords: ["kriminal", "pencurian", "kecelakaan", "polisi", "keamanan", "kdrt", "perkelahian", "maling"],
    icon: `<img src="assets/polda-jateng.png" alt="Logo POLDA JATENG" class="service-logo-img" />`,
    color: "#1E3A8A",
    bgColor: "#EFF6FF",
    borderColor: "#BFDBFE",
  },
  {
    id: "damkar-baturetno",
    name: "Damkar Pos Baturetno",
    shortName: "DAMKAR BTR",
    category: "kebakaran",
    categoryLabel: "Pemadam Kebakaran",
    phone: "(0273) 4632911",
    phoneDisplay: "(0273) 4632911",
    phoneRaw: "+6227346329110",
    whatsapp: "+6282310700113", // WA Damkar Pos Baturetno
    description:
      "Pemadam Kebakaran Pos Baturetno (terdekat dari Pracimantoro). Penanganan kebakaran rumah, gedung, lahan pertanian/hutan. Evakuasi hewan berbahaya seperti ular dan tawon vespa. Penyelamatan korban terjebak dan pohon tumbang.",
    keywords: ["kebakaran", "api", "asap", "ular", "tawon", "evakuasi", "pohon tumbang", "terjebak", "baturetno"],
    icon: `<img src="assets/damkar.png" alt="Logo Damkar" class="service-logo-img" />`,
    color: "#9A3412",
    bgColor: "#FFF7ED",
    borderColor: "#FED7AA",
  },
  {
    id: "damkar-wonogiri",
    name: "Damkar Induk Wonogiri",
    shortName: "DAMKAR WNR",
    category: "kebakaran",
    categoryLabel: "Pemadam Kebakaran",
    phone: "(0273) 322013",
    phoneDisplay: "(0273) 322013",
    phoneRaw: "+62273322013",
    whatsapp: "+6285642188002",
    description:
      "Dinas Pemadam Kebakaran Kabupaten Wonogiri (Pos Induk). Penanganan kebakaran skala besar, koordinasi antar pos damkar, rescue darurat, evakuasi bangunan runtuh, dan penanganan bahan berbahaya.",
    keywords: ["kebakaran", "api", "asap", "damkar", "wonogiri", "rescue", "bangunan runtuh"],
    icon: `<img src="assets/damkar.png" alt="Logo Damkar Induk Wonogiri" class="service-logo-img" />`,
    color: "#991B1B",
    bgColor: "#FEF2F2",
    borderColor: "#FECACA",
  },
  {
    id: "puskesmas-1",
    name: "Puskesmas Pracimantoro 1",
    shortName: "PKM 1",
    category: "medis",
    categoryLabel: "Medis & Ambulans",
    phone: "(0273) 461415",
    phoneDisplay: "(0273) 461415",
    phoneRaw: "+62273461415",
    whatsapp: "+628112653251",
    description:
      "Layanan ambulans darurat 24 jam, pertolongan pertama gawat darurat (UGD), dan rujukan pasien kritis. Melayani wilayah kerja Pracimantoro bagian barat dan utara.",
    keywords: ["ambulans", "ugd", "medis", "dokter", "darurat", "sakit", "kecelakaan", "puskesmas", "praci 1"],
    icon: `<img src="assets/puskesmas.png" alt="Logo UPTD Puskesmas" class="service-logo-img" />`,
    color: "#065F46",
    bgColor: "#ECFDF5",
    borderColor: "#A7F3D0",
  },
  {
    id: "puskesmas-2",
    name: "Puskesmas Pracimantoro 2",
    shortName: "PKM 2",
    category: "medis",
    categoryLabel: "Medis & Ambulans",
    phone: "0895393319589",
    phoneDisplay: "0895-3933-19589",
    phoneRaw: "+62895393319589",
    whatsapp: "+62895393319589",
    description:
      "Layanan ambulans darurat 24 jam, pertolongan pertama gawat darurat, dan rujukan pasien. Melayani wilayah kerja Pracimantoro bagian timur dan selatan.",
    keywords: ["ambulans", "ugd", "medis", "dokter", "darurat", "sakit", "kecelakaan", "puskesmas", "praci 2"],
    icon: `<img src="assets/puskesmas.png" alt="Logo UPTD Puskesmas" class="service-logo-img" />`,
    color: "#134E4A",
    bgColor: "#F0FDFA",
    borderColor: "#99F6E4",
  },
  {
    id: "bpbd-wonogiri",
    name: "BPBD Kabupaten Wonogiri",
    shortName: "BPBD",
    category: "bencana",
    categoryLabel: "Bencana Alam",
    phone: "(0273) 323184",
    phoneDisplay: "(0273) 323184",
    phoneRaw: "+62273323184",
    whatsapp: "+6285171189112", // WA BPBD Wonogiri
    description:
      "Badan Penanggulangan Bencana Daerah. Penanganan bencana alam: tanah longsor, banjir, kekeringan dan krisis air bersih, angin puting beliung, gempa bumi, serta koordinasi pengungsian korban bencana.",
    keywords: ["longsor", "banjir", "bencana", "gempa", "angin", "puting beliung", "kekeringan", "air bersih", "pengungsian"],
    icon: `<img src="assets/bpbd.png" alt="Logo BPBD Wonogiri" class="service-logo-img" />`,
    color: "#92400E",
    bgColor: "#FFFBEB",
    borderColor: "#FDE68A",
  },
  {
    id: "sar-wonogiri",
    name: "SAR Wonogiri",
    shortName: "SAR",
    category: "bencana",
    categoryLabel: "Pencarian & Penyelamatan",
    phone: "(0273) 321090",
    phoneDisplay: "(0273) 321090",
    phoneRaw: "+62273321090",
    whatsapp: "+628126000115", // WA SAR Wonogiri
    description:
      "Search and Rescue. Operasi pencarian dan pertolongan korban tenggelam di perairan, waduk, dan sungai. Evakuasi orang hilang di hutan/kawasan karst Gunung Sewu. Penyelamatan di medan ekstrem dan terpencil.",
    keywords: ["tenggelam", "hilang", "hutan", "karst", "sar", "selamatkan", "evakuasi", "waduk", "sungai", "gunung"],
    icon: `<img src="assets/sar.png" alt="Logo SAR Wonogiri" class="service-logo-img" />`,
    color: "#0C4A6E",
    bgColor: "#F0F9FF",
    borderColor: "#BAE6FD",
  },
  {
    id: "dishub-wonogiri",
    name: "DISHUB Wonogiri",
    shortName: "DISHUB",
    category: "lalin",
    categoryLabel: "Lalu Lintas & Jalan",
    phone: "(0273) 321147",
    phoneDisplay: "(0273) 321147 / WA: 0811-2707-147",
    phoneRaw: "+62273321147",
    whatsapp: "+628112707147",
    description:
      "Dinas Perhubungan Wonogiri. Gangguan lampu penerangan jalan umum (PJU) mati, rambu lalu lintas rusak/hilang, penertiban kemacetan ekstrem, koordinasi jalur alternatif, serta rekayasa lalu lintas darurat.",
    keywords: ["lampu jalan", "pju", "macet", "rambu", "dishub", "kemacetan", "jalan", "lalin", "mudik", "penerangan"],
    icon: `<img src="assets/dishub.png" alt="Logo DISHUB Wonogiri" class="service-logo-img" />`,
    color: "#4C1D95",
    bgColor: "#F5F3FF",
    borderColor: "#DDD6FE",
  },
  {
    id: "pmi-wonogiri",
    name: "PMI Wonogiri",
    shortName: "PMI",
    category: "medis",
    categoryLabel: "Medis & Kemanusiaan",
    phone: "(0273) 321123",
    phoneDisplay: "(0273) 321123",
    phoneRaw: "+62273321123",
    whatsapp: "+6281327054358", // WA PMI Wonogiri
    description:
      "Palang Merah Indonesia Wonogiri. Bantuan donor darah darurat 24 jam, layanan ambulans jenazah dan pasien, posko pertolongan pertama saat bencana, dan bantuan kemanusiaan tanggap darurat untuk korban bencana.",
    keywords: ["darah", "donor", "pmi", "ambulans", "jenazah", "palang merah", "kemanusiaan", "bencana"],
    icon: `<img src="assets/pmi.png" alt="Logo PMI Wonogiri" class="service-logo-img" />`,
    color: "#881337",
    bgColor: "#FFF1F2",
    borderColor: "#FECDD3",
  },
  {
    id: "relawan-prabu",
    name: "Relawan PRABU (Pracimantoro Bersatu)",
    shortName: "PRABU",
    category: "bencana",
    categoryLabel: "Relawan & Kedaruratan",
    phone: "0852-9232-3230",
    phoneDisplay: "0852-9232-3230 / 0878-4154-2664",
    phoneRaw: "+6285292323230",
    whatsapp: "+6285292323230",
    contacts: [
      {
        name: "Saryono",
        phone: "0852-9232-3230",
        phoneRaw: "+6285292323230",
        whatsapp: "+6285292323230",
      },
      {
        name: "Rudi",
        phone: "0878-4154-2664",
        phoneRaw: "+6287841542664",
        whatsapp: "+6287841542664",
      },
    ],
    description:
      "Organisasi Relawan PRABU (Pracimantoro Bersatu). Siaga aksi cepat tanggap bencana alam, evakuasi warga terdampak, penanganan pohon tumbang, bantuan sosial darurat kemanusiaan, dan pertolongan pertama kedaruratan di wilayah Kecamatan Pracimantoro.",
    keywords: [
      "relawan",
      "prabu",
      "pracimantoro bersatu",
      "saryono",
      "rudi",
      "bencana",
      "evakuasi",
      "pohon tumbang",
      "longsor",
      "banjir",
      "siaga",
      "pertolongan",
    ],
    icon: `<img src="assets/logo-prabu.png" alt="Logo Relawan PRABU" class="service-logo-img" />`,
    color: "#D97706",
    bgColor: "#FFFBEB",
    borderColor: "#FDE68A",
  },
];

const CATEGORIES = [
  { id: "semua", label: "Semua Layanan", icon: "" },
  { id: "medis", label: "Medis & Ambulans", icon: "" },
  { id: "keamanan", label: "Keamanan (Polisi)", icon: "" },
  { id: "kebakaran", label: "Kebakaran & Evakuasi", icon: "" },
  { id: "bencana", label: "Bencana & SAR", icon: "" },
  { id: "lalin", label: "Lalu Lintas / Dishub", icon: "" },
];

// Panduan Pertolongan Pertama Singkat
const FIRST_AID_GUIDES = [
  {
    id: "kebakaran",
    title: "Saat Terjadi Kebakaran",
    icon: "🔥",
    color: "#DC2626",
    bgColor: "#FEF2F2",
    steps: [
      "Segera hubungi Damkar — Pos Baturetno: (0273) 4632911",
      "Jangan panik — evakuasi diri dan orang sekitar dahulu",
      "Tutup mulut & hidung dengan kain basah jika ada asap",
      "Matikan sumber listrik dari panel utama jika memungkinkan",
      "Jangan gunakan lift — gunakan tangga darurat",
      "Kumpulkan di titik aman, jangan kembali masuk gedung",
    ],
  },
  {
    id: "kecelakaan",
    title: "Saat Terjadi Kecelakaan",
    icon: "🚗",
    color: "#D97706",
    bgColor: "#FFFBEB",
    steps: [
      "Hubungi ambulans Puskesmas & Polisi (110) segera",
      "Pastikan keamanan lokasi, nyalakan lampu hazard",
      "Jangan pindahkan korban kecuali ada bahaya langsung",
      "Hentikan perdarahan dengan tekanan kain bersih",
      "Jaga korban tetap sadar, ajak berbicara",
      "Dokumentasi nomor kendaraan & saksi untuk polisi",
    ],
  },
  {
    id: "tenggelam",
    title: "Saat Ada Orang Tenggelam",
    icon: "🌊",
    color: "#0369A1",
    bgColor: "#F0F9FF",
    steps: [
      "Hubungi SAR Wonogiri: (0273) 321090 segera",
      "Lempar pelampung, tali, atau papan — jangan langsung terjun kecuali terlatih",
      "Setelah korban diangkat, miringkan tubuh untuk keluarkan air",
      "Lakukan CPR jika tidak ada nafas & denyut nadi",
      "Jaga korban tetap hangat, segera bawa ke Puskesmas",
    ],
  },
  {
    id: "bencana",
    title: "Saat Terjadi Bencana Alam",
    icon: "⛰️",
    color: "#7C3AED",
    bgColor: "#F5F3FF",
    steps: [
      "Hubungi BPBD Wonogiri: (0273) 323184 segera",
      "Jauhi area longsor, sungai banjir, atau bangunan rusak",
      "Matikan gas, listrik, dan air sebelum mengungsi",
      "Bawa dokumen penting dalam tas siaga bencana",
      "Ikuti arahan petugas BPBD dan tidak kembali sebelum aman",
      "Informasikan kondisi warga lain yang membutuhkan bantuan",
    ],
  },
];
